plugins:
  - jekyll-relative-links
  - jemoji  
remote_theme: pages-themes/tactile@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
mermaid:
  src: '/js/mermaid.js'
  src_config: '/js/mermaid_config.js'
